### ISSUE TITLE
iOS 9 support 

### ISSUE THREAD

**Issue by OmgImAlexis** [twotreeszf/PrettyTunnel#2]
Does this currently work with iOS 9 or do you plan on updating this to make it work?

**Comment by OmgImAlexis** [comment]
@twotreeszf any updates on this? Same goes for iOS 10

**Comment by twotreeszf** [comment]
Sorry, Recently I'm not have enough time to work on this, Maybe sometime in
the future can do. I hope you can tell me where the problem,Perhaps I can
offer same simple solutions.

2016-10-10 9:52 GMT+08:00 X O notifications@github.com:

**Comment by liaogang** [comment]
The private api about iOS proxy setting will not apply the changes until the app have root privileges if using iOS9,10.

**Comment by twotreeszf** [comment]
Maybe, the feature I'm not tested on iOS 9 and above.

2018-04-13 16:30 GMT+08:00 gz3z <notifications@github.com>:
